[package]
name = "async_http"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6", features = ["runtime-async-std-native-tls", "postgres"] }
async-std = { version = "1", features = ["attributes"] }
