[package]
name = "async_http"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6", features = ["runtime-async-std-native-tls", "postgres"] }
async-std = { version = "1", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.23"
futures = "0.3.0"
regex = "1"