[package]
name    = "chatgpt"
version = "0.1.0"
edition = "2021"

[dependencies]
ohkami  = { workspace = true }
tokio   = { workspace = true }
reqwest = { version = "0.12", features = ["json", "stream"] }

[features]
DEBUG = ["ohkami/DEBUG"]