[lib]
proc-macro = true

[package]
name          = "ohkami_macros"
version       = "0.5.1"
edition       = "2021"
authors       = ["kanarus <kanarus786@gmail.com>"]
description   = "Proc macros for ohkami - intuitive and declarative web framework"
documentation = "https://docs.rs/ohkami"
homepage      = "https://crates.io/crates/ohkami"
repository    = "https://github.com/kana-rus/ohkami"
keywords      = ["async", "http", "web", "server", "framework"]
categories    = ["rust-patterns", "asynchronous", "web-programming::http-server"]
license       = "MIT"
readme        = "../README.md"

[dependencies]
proc-macro2   = "1.0"
quote         = "1.0"
syn           = { version = "1.0", features = ["full"] }